package tafargumentlistenererrortypes

type TAFArgumentListenerError int

const (
	DIVISION_BY_ZERO TAFArgumentListenerError = iota
	UNDECLARED_VARIABLE
	RUNTIME_ERROR
	NONE
	CONVERSION_ERROR
	UNKNOWN_CONVERSION_ERROR
	INVALID_OPERATION_ERROR
	OPERATION_NOT_SUPPORTED_ERROR
	JSON_OBJECT_IMPORT_ERROR
	JSON_ARRAY_IMPORT_ERROR
)
